name: muppen64plus # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: mupen64plus - the Nintendo 64 emulator
description: |
  mupen64plus - the Nintendo 64 emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mupen64plus_icon.png
title: Mupen64plus

apps:
  mupen64plus:
    command: mupen64plus
parts:
  mupen64plus:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mupen64plus: build/
      mupen64plus.1: man/man1/

architectures:
  - build-on: amd64

