name: muppen64plus # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: muppen64plus - the Nintendo 64 emulator
description: |
  muppen64plus - the Nintendo 64 emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  muppen64plus_icon.png
title: Mupen64plus

apps:
  muppen64plus:
    command: muppen64plus
parts:
  muppen64plus:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      muppen64plus: build/
      muppen64plus.1: man/man1/

architectures:
  - build-on: amd64

